export const SentenceTypes = {
  FETCH_SENTENCE: 'FETCH_SENTENCE',
  FETCH_NEXT_SENTENCE: 'FETCH_NEXT_SENTENCE',
  SCRAMBLED_SENTENCE: 'SCRAMBLED_SENTENCE',
  INCREASE_SCORE: 'INCREASE_SCORE',
  RESET: 'RESET',
  NEXT_LETTER: 'NEXT_LETTER',
  PREV_LETTER: 'PREV_LETTER',
  SHOW_NEXT_BTN: 'SHOW_NEXT_BTN',
  ADD_TO_CORRECT: 'ADD_TO_CORRECT',
  ADD_TO_WRONG: 'ADD_TO_WRONG',
  REMOVE_FROM_WRONG: 'REMOVE_FROM_WRONG',
  CHECK_SENTENCE: 'CHECK_SENTENCE',
};
